/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// VehicleBreak struct for VehicleBreak
type VehicleBreak struct {
	DriveTimeBreak *DriveTimeBreak
	TimeWindowBreak *TimeWindowBreak
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *VehicleBreak) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into DriveTimeBreak
	err = json.Unmarshal(data, &dst.DriveTimeBreak);
	if err == nil {
		jsonDriveTimeBreak, _ := json.Marshal(dst.DriveTimeBreak)
		if string(jsonDriveTimeBreak) == "{}" { // empty struct
			dst.DriveTimeBreak = nil
		} else {
			return nil // data stored in dst.DriveTimeBreak, return on the first match
		}
	} else {
		dst.DriveTimeBreak = nil
	}

	// try to unmarshal JSON data into TimeWindowBreak
	err = json.Unmarshal(data, &dst.TimeWindowBreak);
	if err == nil {
		jsonTimeWindowBreak, _ := json.Marshal(dst.TimeWindowBreak)
		if string(jsonTimeWindowBreak) == "{}" { // empty struct
			dst.TimeWindowBreak = nil
		} else {
			return nil // data stored in dst.TimeWindowBreak, return on the first match
		}
	} else {
		dst.TimeWindowBreak = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(VehicleBreak)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VehicleBreak) MarshalJSON() ([]byte, error) {
	if src.DriveTimeBreak != nil {
		return json.Marshal(&src.DriveTimeBreak)
	}

	if src.TimeWindowBreak != nil {
		return json.Marshal(&src.TimeWindowBreak)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableVehicleBreak struct {
	value *VehicleBreak
	isSet bool
}

func (v NullableVehicleBreak) Get() *VehicleBreak {
	return v.value
}

func (v *NullableVehicleBreak) Set(val *VehicleBreak) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleBreak) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleBreak) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleBreak(val *VehicleBreak) *NullableVehicleBreak {
	return &NullableVehicleBreak{value: val, isSet: true}
}

func (v NullableVehicleBreak) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleBreak) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


