/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Configuration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelConfiguration{}

// Configuration Specifies general configurations that are taken into account when solving the vehicle routing problem.
type ModelConfiguration struct {
	Routing *Routing `json:"routing,omitempty"`
	Optimization *Optimization `json:"optimization,omitempty"`
}

// NewConfiguration instantiates a new Configuration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelConfiguration() *ModelConfiguration {
	this := ModelConfiguration{}
	return &this
}

// NewConfigurationWithDefaults instantiates a new Configuration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationWithDefaults() *ModelConfiguration {
	this := ModelConfiguration{}
	return &this
}

// GetRouting returns the Routing field value if set, zero value otherwise.
func (o *ModelConfiguration) GetRouting() Routing {
	if o == nil || IsNil(o.Routing) {
		var ret Routing
		return ret
	}
	return *o.Routing
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelConfiguration) GetRoutingOk() (*Routing, bool) {
	if o == nil || IsNil(o.Routing) {
		return nil, false
	}
	return o.Routing, true
}

// HasRouting returns a boolean if a field has been set.
func (o *ModelConfiguration) HasRouting() bool {
	if o != nil && !IsNil(o.Routing) {
		return true
	}

	return false
}

// SetRouting gets a reference to the given Routing and assigns it to the Routing field.
func (o *ModelConfiguration) SetRouting(v Routing) {
	o.Routing = &v
}

// GetOptimization returns the Optimization field value if set, zero value otherwise.
func (o *ModelConfiguration) GetOptimization() Optimization {
	if o == nil || IsNil(o.Optimization) {
		var ret Optimization
		return ret
	}
	return *o.Optimization
}

// GetOptimizationOk returns a tuple with the Optimization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelConfiguration) GetOptimizationOk() (*Optimization, bool) {
	if o == nil || IsNil(o.Optimization) {
		return nil, false
	}
	return o.Optimization, true
}

// HasOptimization returns a boolean if a field has been set.
func (o *ModelConfiguration) HasOptimization() bool {
	if o != nil && !IsNil(o.Optimization) {
		return true
	}

	return false
}

// SetOptimization gets a reference to the given Optimization and assigns it to the Optimization field.
func (o *ModelConfiguration) SetOptimization(v Optimization) {
	o.Optimization = &v
}

func (o ModelConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Routing) {
		toSerialize["routing"] = o.Routing
	}
	if !IsNil(o.Optimization) {
		toSerialize["optimization"] = o.Optimization
	}
	return toSerialize, nil
}

type NullableConfiguration struct {
	value *ModelConfiguration
	isSet bool
}

func (v NullableConfiguration) Get() *ModelConfiguration {
	return v.value
}

func (v *NullableConfiguration) Set(val *ModelConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfiguration(val *ModelConfiguration) *NullableConfiguration {
	return &NullableConfiguration{value: val, isSet: true}
}

func (v NullableConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


