/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GHError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GHError{}

// GHError struct for GHError
type GHError struct {
	Message *string `json:"message,omitempty"`
	// Optional error information.
	Hints []GHErrorHintsInner `json:"hints,omitempty"`
}

// NewGHError instantiates a new GHError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGHError() *GHError {
	this := GHError{}
	return &this
}

// NewGHErrorWithDefaults instantiates a new GHError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGHErrorWithDefaults() *GHError {
	this := GHError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GHError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GHError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GHError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GHError) SetMessage(v string) {
	o.Message = &v
}

// GetHints returns the Hints field value if set, zero value otherwise.
func (o *GHError) GetHints() []GHErrorHintsInner {
	if o == nil || IsNil(o.Hints) {
		var ret []GHErrorHintsInner
		return ret
	}
	return o.Hints
}

// GetHintsOk returns a tuple with the Hints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GHError) GetHintsOk() ([]GHErrorHintsInner, bool) {
	if o == nil || IsNil(o.Hints) {
		return nil, false
	}
	return o.Hints, true
}

// HasHints returns a boolean if a field has been set.
func (o *GHError) HasHints() bool {
	if o != nil && !IsNil(o.Hints) {
		return true
	}

	return false
}

// SetHints gets a reference to the given []GHErrorHintsInner and assigns it to the Hints field.
func (o *GHError) SetHints(v []GHErrorHintsInner) {
	o.Hints = v
}

func (o GHError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GHError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Hints) {
		toSerialize["hints"] = o.Hints
	}
	return toSerialize, nil
}

type NullableGHError struct {
	value *GHError
	isSet bool
}

func (v NullableGHError) Get() *GHError {
	return v.value
}

func (v *NullableGHError) Set(val *GHError) {
	v.value = val
	v.isSet = true
}

func (v NullableGHError) IsSet() bool {
	return v.isSet
}

func (v *NullableGHError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGHError(val *GHError) *NullableGHError {
	return &NullableGHError{value: val, isSet: true}
}

func (v NullableGHError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGHError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


