/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SnappedWaypoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnappedWaypoint{}

// SnappedWaypoint Access point to the (road)network. It is only available if `return_snapped_waypoints` is true (be default it is false).
type SnappedWaypoint struct {
	// Longitude of location.
	Lon *float64 `json:"lon,omitempty"`
	// Latitude of location.
	Lat *float64 `json:"lat,omitempty"`
}

// NewSnappedWaypoint instantiates a new SnappedWaypoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnappedWaypoint() *SnappedWaypoint {
	this := SnappedWaypoint{}
	return &this
}

// NewSnappedWaypointWithDefaults instantiates a new SnappedWaypoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnappedWaypointWithDefaults() *SnappedWaypoint {
	this := SnappedWaypoint{}
	return &this
}

// GetLon returns the Lon field value if set, zero value otherwise.
func (o *SnappedWaypoint) GetLon() float64 {
	if o == nil || IsNil(o.Lon) {
		var ret float64
		return ret
	}
	return *o.Lon
}

// GetLonOk returns a tuple with the Lon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnappedWaypoint) GetLonOk() (*float64, bool) {
	if o == nil || IsNil(o.Lon) {
		return nil, false
	}
	return o.Lon, true
}

// HasLon returns a boolean if a field has been set.
func (o *SnappedWaypoint) HasLon() bool {
	if o != nil && !IsNil(o.Lon) {
		return true
	}

	return false
}

// SetLon gets a reference to the given float64 and assigns it to the Lon field.
func (o *SnappedWaypoint) SetLon(v float64) {
	o.Lon = &v
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *SnappedWaypoint) GetLat() float64 {
	if o == nil || IsNil(o.Lat) {
		var ret float64
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnappedWaypoint) GetLatOk() (*float64, bool) {
	if o == nil || IsNil(o.Lat) {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *SnappedWaypoint) HasLat() bool {
	if o != nil && !IsNil(o.Lat) {
		return true
	}

	return false
}

// SetLat gets a reference to the given float64 and assigns it to the Lat field.
func (o *SnappedWaypoint) SetLat(v float64) {
	o.Lat = &v
}

func (o SnappedWaypoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnappedWaypoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lon) {
		toSerialize["lon"] = o.Lon
	}
	if !IsNil(o.Lat) {
		toSerialize["lat"] = o.Lat
	}
	return toSerialize, nil
}

type NullableSnappedWaypoint struct {
	value *SnappedWaypoint
	isSet bool
}

func (v NullableSnappedWaypoint) Get() *SnappedWaypoint {
	return v.value
}

func (v *NullableSnappedWaypoint) Set(val *SnappedWaypoint) {
	v.value = val
	v.isSet = true
}

func (v NullableSnappedWaypoint) IsSet() bool {
	return v.isSet
}

func (v *NullableSnappedWaypoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnappedWaypoint(val *SnappedWaypoint) *NullableSnappedWaypoint {
	return &NullableSnappedWaypoint{value: val, isSet: true}
}

func (v NullableSnappedWaypoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnappedWaypoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


