/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetMatrixSolution200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMatrixSolution200Response{}

// GetMatrixSolution200Response struct for GetMatrixSolution200Response
type GetMatrixSolution200Response struct {
	Solution *MatrixResponse `json:"solution,omitempty"`
}

// NewGetMatrixSolution200Response instantiates a new GetMatrixSolution200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMatrixSolution200Response() *GetMatrixSolution200Response {
	this := GetMatrixSolution200Response{}
	return &this
}

// NewGetMatrixSolution200ResponseWithDefaults instantiates a new GetMatrixSolution200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMatrixSolution200ResponseWithDefaults() *GetMatrixSolution200Response {
	this := GetMatrixSolution200Response{}
	return &this
}

// GetSolution returns the Solution field value if set, zero value otherwise.
func (o *GetMatrixSolution200Response) GetSolution() MatrixResponse {
	if o == nil || IsNil(o.Solution) {
		var ret MatrixResponse
		return ret
	}
	return *o.Solution
}

// GetSolutionOk returns a tuple with the Solution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMatrixSolution200Response) GetSolutionOk() (*MatrixResponse, bool) {
	if o == nil || IsNil(o.Solution) {
		return nil, false
	}
	return o.Solution, true
}

// HasSolution returns a boolean if a field has been set.
func (o *GetMatrixSolution200Response) HasSolution() bool {
	if o != nil && !IsNil(o.Solution) {
		return true
	}

	return false
}

// SetSolution gets a reference to the given MatrixResponse and assigns it to the Solution field.
func (o *GetMatrixSolution200Response) SetSolution(v MatrixResponse) {
	o.Solution = &v
}

func (o GetMatrixSolution200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMatrixSolution200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Solution) {
		toSerialize["solution"] = o.Solution
	}
	return toSerialize, nil
}

type NullableGetMatrixSolution200Response struct {
	value *GetMatrixSolution200Response
	isSet bool
}

func (v NullableGetMatrixSolution200Response) Get() *GetMatrixSolution200Response {
	return v.value
}

func (v *NullableGetMatrixSolution200Response) Set(val *GetMatrixSolution200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMatrixSolution200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMatrixSolution200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMatrixSolution200Response(val *GetMatrixSolution200Response) *NullableGetMatrixSolution200Response {
	return &NullableGetMatrixSolution200Response{value: val, isSet: true}
}

func (v NullableGetMatrixSolution200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMatrixSolution200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


