/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MatrixResponseHintsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatrixResponseHintsInner{}

// MatrixResponseHintsInner struct for MatrixResponseHintsInner
type MatrixResponseHintsInner struct {
	// Short description of this hint
	Message *string `json:"message,omitempty"`
	// Details of this hint
	Details *string `json:"details,omitempty"`
	// Optional. An array of from_point indices of points that could not be found. Will only be added if `fail_fast=false` and some `from_point`s were not found.`
	InvalidFromPoints []float32 `json:"invalid_from_points,omitempty"`
	// Optional. An array of to_point indices of points that could not be found. Will only be added if `fail_fast=false` and some `to_point`s were not found.`
	InvalidToPoints []float32 `json:"invalid_to_points,omitempty"`
	// Optional. An array of two-element arrays representing the from/to_point indices of points for which no connection could be found. Will only be added if `fail_fast=false` and some connections were not found.
	PointPairs [][]float32 `json:"point_pairs,omitempty"`
}

// NewMatrixResponseHintsInner instantiates a new MatrixResponseHintsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatrixResponseHintsInner() *MatrixResponseHintsInner {
	this := MatrixResponseHintsInner{}
	return &this
}

// NewMatrixResponseHintsInnerWithDefaults instantiates a new MatrixResponseHintsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatrixResponseHintsInnerWithDefaults() *MatrixResponseHintsInner {
	this := MatrixResponseHintsInner{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MatrixResponseHintsInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixResponseHintsInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MatrixResponseHintsInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MatrixResponseHintsInner) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *MatrixResponseHintsInner) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixResponseHintsInner) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *MatrixResponseHintsInner) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *MatrixResponseHintsInner) SetDetails(v string) {
	o.Details = &v
}

// GetInvalidFromPoints returns the InvalidFromPoints field value if set, zero value otherwise.
func (o *MatrixResponseHintsInner) GetInvalidFromPoints() []float32 {
	if o == nil || IsNil(o.InvalidFromPoints) {
		var ret []float32
		return ret
	}
	return o.InvalidFromPoints
}

// GetInvalidFromPointsOk returns a tuple with the InvalidFromPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixResponseHintsInner) GetInvalidFromPointsOk() ([]float32, bool) {
	if o == nil || IsNil(o.InvalidFromPoints) {
		return nil, false
	}
	return o.InvalidFromPoints, true
}

// HasInvalidFromPoints returns a boolean if a field has been set.
func (o *MatrixResponseHintsInner) HasInvalidFromPoints() bool {
	if o != nil && !IsNil(o.InvalidFromPoints) {
		return true
	}

	return false
}

// SetInvalidFromPoints gets a reference to the given []float32 and assigns it to the InvalidFromPoints field.
func (o *MatrixResponseHintsInner) SetInvalidFromPoints(v []float32) {
	o.InvalidFromPoints = v
}

// GetInvalidToPoints returns the InvalidToPoints field value if set, zero value otherwise.
func (o *MatrixResponseHintsInner) GetInvalidToPoints() []float32 {
	if o == nil || IsNil(o.InvalidToPoints) {
		var ret []float32
		return ret
	}
	return o.InvalidToPoints
}

// GetInvalidToPointsOk returns a tuple with the InvalidToPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixResponseHintsInner) GetInvalidToPointsOk() ([]float32, bool) {
	if o == nil || IsNil(o.InvalidToPoints) {
		return nil, false
	}
	return o.InvalidToPoints, true
}

// HasInvalidToPoints returns a boolean if a field has been set.
func (o *MatrixResponseHintsInner) HasInvalidToPoints() bool {
	if o != nil && !IsNil(o.InvalidToPoints) {
		return true
	}

	return false
}

// SetInvalidToPoints gets a reference to the given []float32 and assigns it to the InvalidToPoints field.
func (o *MatrixResponseHintsInner) SetInvalidToPoints(v []float32) {
	o.InvalidToPoints = v
}

// GetPointPairs returns the PointPairs field value if set, zero value otherwise.
func (o *MatrixResponseHintsInner) GetPointPairs() [][]float32 {
	if o == nil || IsNil(o.PointPairs) {
		var ret [][]float32
		return ret
	}
	return o.PointPairs
}

// GetPointPairsOk returns a tuple with the PointPairs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixResponseHintsInner) GetPointPairsOk() ([][]float32, bool) {
	if o == nil || IsNil(o.PointPairs) {
		return nil, false
	}
	return o.PointPairs, true
}

// HasPointPairs returns a boolean if a field has been set.
func (o *MatrixResponseHintsInner) HasPointPairs() bool {
	if o != nil && !IsNil(o.PointPairs) {
		return true
	}

	return false
}

// SetPointPairs gets a reference to the given [][]float32 and assigns it to the PointPairs field.
func (o *MatrixResponseHintsInner) SetPointPairs(v [][]float32) {
	o.PointPairs = v
}

func (o MatrixResponseHintsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatrixResponseHintsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.InvalidFromPoints) {
		toSerialize["invalid_from_points"] = o.InvalidFromPoints
	}
	if !IsNil(o.InvalidToPoints) {
		toSerialize["invalid_to_points"] = o.InvalidToPoints
	}
	if !IsNil(o.PointPairs) {
		toSerialize["point_pairs"] = o.PointPairs
	}
	return toSerialize, nil
}

type NullableMatrixResponseHintsInner struct {
	value *MatrixResponseHintsInner
	isSet bool
}

func (v NullableMatrixResponseHintsInner) Get() *MatrixResponseHintsInner {
	return v.value
}

func (v *NullableMatrixResponseHintsInner) Set(val *MatrixResponseHintsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMatrixResponseHintsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMatrixResponseHintsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatrixResponseHintsInner(val *MatrixResponseHintsInner) *NullableMatrixResponseHintsInner {
	return &NullableMatrixResponseHintsInner{value: val, isSet: true}
}

func (v NullableMatrixResponseHintsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatrixResponseHintsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


