/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CostMatrixData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostMatrixData{}

// CostMatrixData JSON data of matrix response
type CostMatrixData struct {
	Times [][]int64 `json:"times,omitempty"`
	Distances [][]float64 `json:"distances,omitempty"`
	Info *CostMatrixDataInfo `json:"info,omitempty"`
}

// NewCostMatrixData instantiates a new CostMatrixData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostMatrixData() *CostMatrixData {
	this := CostMatrixData{}
	return &this
}

// NewCostMatrixDataWithDefaults instantiates a new CostMatrixData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostMatrixDataWithDefaults() *CostMatrixData {
	this := CostMatrixData{}
	return &this
}

// GetTimes returns the Times field value if set, zero value otherwise.
func (o *CostMatrixData) GetTimes() [][]int64 {
	if o == nil || IsNil(o.Times) {
		var ret [][]int64
		return ret
	}
	return o.Times
}

// GetTimesOk returns a tuple with the Times field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrixData) GetTimesOk() ([][]int64, bool) {
	if o == nil || IsNil(o.Times) {
		return nil, false
	}
	return o.Times, true
}

// HasTimes returns a boolean if a field has been set.
func (o *CostMatrixData) HasTimes() bool {
	if o != nil && !IsNil(o.Times) {
		return true
	}

	return false
}

// SetTimes gets a reference to the given [][]int64 and assigns it to the Times field.
func (o *CostMatrixData) SetTimes(v [][]int64) {
	o.Times = v
}

// GetDistances returns the Distances field value if set, zero value otherwise.
func (o *CostMatrixData) GetDistances() [][]float64 {
	if o == nil || IsNil(o.Distances) {
		var ret [][]float64
		return ret
	}
	return o.Distances
}

// GetDistancesOk returns a tuple with the Distances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrixData) GetDistancesOk() ([][]float64, bool) {
	if o == nil || IsNil(o.Distances) {
		return nil, false
	}
	return o.Distances, true
}

// HasDistances returns a boolean if a field has been set.
func (o *CostMatrixData) HasDistances() bool {
	if o != nil && !IsNil(o.Distances) {
		return true
	}

	return false
}

// SetDistances gets a reference to the given [][]float64 and assigns it to the Distances field.
func (o *CostMatrixData) SetDistances(v [][]float64) {
	o.Distances = v
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *CostMatrixData) GetInfo() CostMatrixDataInfo {
	if o == nil || IsNil(o.Info) {
		var ret CostMatrixDataInfo
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrixData) GetInfoOk() (*CostMatrixDataInfo, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *CostMatrixData) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given CostMatrixDataInfo and assigns it to the Info field.
func (o *CostMatrixData) SetInfo(v CostMatrixDataInfo) {
	o.Info = &v
}

func (o CostMatrixData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostMatrixData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Times) {
		toSerialize["times"] = o.Times
	}
	if !IsNil(o.Distances) {
		toSerialize["distances"] = o.Distances
	}
	if !IsNil(o.Info) {
		toSerialize["info"] = o.Info
	}
	return toSerialize, nil
}

type NullableCostMatrixData struct {
	value *CostMatrixData
	isSet bool
}

func (v NullableCostMatrixData) Get() *CostMatrixData {
	return v.value
}

func (v *NullableCostMatrixData) Set(val *CostMatrixData) {
	v.value = val
	v.isSet = true
}

func (v NullableCostMatrixData) IsSet() bool {
	return v.isSet
}

func (v *NullableCostMatrixData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostMatrixData(val *CostMatrixData) *NullableCostMatrixData {
	return &NullableCostMatrixData{value: val, isSet: true}
}

func (v NullableCostMatrixData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostMatrixData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


