/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Service type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Service{}

// Service struct for Service
type Service struct {
	// Specifies the id of the service. Ids need to be unique so there must not be two services/shipments with the same id.
	Id string `json:"id"`
	// Specifies type of service. This makes a difference if items are loaded or unloaded, i.e. if one of the size dimensions > 0. If it is specified as `service` or `pickup`, items are loaded and will stay in the vehicle for the rest of the route (and thus consumes capacity for the rest of the route). If it is a `delivery`, items are implicitly loaded at the beginning of the route and will stay in the route until delivery (and thus releases capacity for the rest of the route).
	Type *string `json:"type,omitempty"`
	// Specifies the priority. Can be 1 = high priority to 10 = low priority. Often there are more services/shipments than the available vehicle fleet can handle. Then you can set priorities to differentiate high priority tasks from those that could be left unassigned. I.e. the lower the priority the earlier these tasks are omitted in the solution.
	Priority *int32 `json:"priority,omitempty"`
	// Meaningful name for service, e.g. `\"deliver pizza\"`.
	Name *string `json:"name,omitempty"`
	Address *Address `json:"address,omitempty"`
	// Specifies the duration of the service in seconds, i.e. how long it takes at the customer site.
	Duration *int64 `json:"duration,omitempty"`
	// Specifies the preparation time in seconds. It can be used to model parking lot search time since if you have 3 identical locations in a row, it only falls due once.
	PreparationTime *int64 `json:"preparation_time,omitempty"`
	// Specifies an array of time window objects (see time_window object below). Specify the time either with the recommended Unix time stamp (the number of seconds since 1970-01-01) or you can also count the seconds relative to Monday morning 00:00 and define the whole week in seconds. For example, Monday 9am is then represented by 9hour * 3600sec/hour = 32400. In turn, Wednesday 1pm corresponds to 2day * 24hour/day * 3600sec/hour + 1day * 13hour/day * 3600sec/hour = 219600. See this tutorial for more information.
	TimeWindows []TimeWindow `json:"time_windows,omitempty"`
	// Size can have multiple dimensions and should be in line with the capacity dimension array of the vehicle type. For example, if the item that needs to be delivered has two size dimension, volume and weight, then specify it as follow [ 20, 5 ] assuming a volume of 20 and a weight of 5.
	Size []int32 `json:"size,omitempty"`
	// Specifies an array of required skills, i.e. array of string (not case sensitive). For example, if this service needs to be conducted by a technician having a `drilling_machine` and a `screw_driver` then specify the array as follows: `[\"drilling_machine\",\"screw_driver\"]`. This means that the service can only be done by a vehicle (technician) that has the skills `drilling_machine` AND `screw_driver` in its skill array. Otherwise it remains unassigned.
	RequiredSkills []string `json:"required_skills,omitempty"`
	// Specifies an array of allowed vehicles, i.e. array of vehicle ids. For example, if this service can only be conducted EITHER by `technician_peter` OR `technician_stefan` specify this as follows: `[\"technician_peter\",\"technician_stefan\"]`.
	AllowedVehicles []string `json:"allowed_vehicles,omitempty"`
	// Specifies an array of disallowed vehicles, i.e. array of vehicle ids.
	DisallowedVehicles []string `json:"disallowed_vehicles,omitempty"`
	// Specifies an array of preferred vehicles.
	PreferredVehicles []PreferredVehicle `json:"preferred_vehicles,omitempty"`
	// Specifies the maximum time in seconds a delivery can stay in the vehicle. Currently, it only works with services of \"type\":\"delivery\".
	MaxTimeInVehicle *int64 `json:"max_time_in_vehicle,omitempty"`
	// Group this service belongs to. See the group relation and [this post](https://discuss.graphhopper.com/t/4040) on how to utilize this.
	Group *string `json:"group,omitempty"`
}

type _Service Service

// NewService instantiates a new Service object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewService(id string) *Service {
	this := Service{}
	this.Id = id
	var type_ string = "service"
	this.Type = &type_
	var priority int32 = 2
	this.Priority = &priority
	var duration int64 = 0
	this.Duration = &duration
	var preparationTime int64 = 0
	this.PreparationTime = &preparationTime
	var maxTimeInVehicle int64 = 9223372036854775807
	this.MaxTimeInVehicle = &maxTimeInVehicle
	return &this
}

// NewServiceWithDefaults instantiates a new Service object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceWithDefaults() *Service {
	this := Service{}
	var type_ string = "service"
	this.Type = &type_
	var priority int32 = 2
	this.Priority = &priority
	var duration int64 = 0
	this.Duration = &duration
	var preparationTime int64 = 0
	this.PreparationTime = &preparationTime
	var maxTimeInVehicle int64 = 9223372036854775807
	this.MaxTimeInVehicle = &maxTimeInVehicle
	return &this
}

// GetId returns the Id field value
func (o *Service) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Service) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Service) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Service) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Service) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Service) SetType(v string) {
	o.Type = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *Service) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *Service) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *Service) SetPriority(v int32) {
	o.Priority = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Service) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Service) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Service) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Service) GetAddress() Address {
	if o == nil || IsNil(o.Address) {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAddressOk() (*Address, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Service) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *Service) SetAddress(v Address) {
	o.Address = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *Service) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *Service) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *Service) SetDuration(v int64) {
	o.Duration = &v
}

// GetPreparationTime returns the PreparationTime field value if set, zero value otherwise.
func (o *Service) GetPreparationTime() int64 {
	if o == nil || IsNil(o.PreparationTime) {
		var ret int64
		return ret
	}
	return *o.PreparationTime
}

// GetPreparationTimeOk returns a tuple with the PreparationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetPreparationTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.PreparationTime) {
		return nil, false
	}
	return o.PreparationTime, true
}

// HasPreparationTime returns a boolean if a field has been set.
func (o *Service) HasPreparationTime() bool {
	if o != nil && !IsNil(o.PreparationTime) {
		return true
	}

	return false
}

// SetPreparationTime gets a reference to the given int64 and assigns it to the PreparationTime field.
func (o *Service) SetPreparationTime(v int64) {
	o.PreparationTime = &v
}

// GetTimeWindows returns the TimeWindows field value if set, zero value otherwise.
func (o *Service) GetTimeWindows() []TimeWindow {
	if o == nil || IsNil(o.TimeWindows) {
		var ret []TimeWindow
		return ret
	}
	return o.TimeWindows
}

// GetTimeWindowsOk returns a tuple with the TimeWindows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetTimeWindowsOk() ([]TimeWindow, bool) {
	if o == nil || IsNil(o.TimeWindows) {
		return nil, false
	}
	return o.TimeWindows, true
}

// HasTimeWindows returns a boolean if a field has been set.
func (o *Service) HasTimeWindows() bool {
	if o != nil && !IsNil(o.TimeWindows) {
		return true
	}

	return false
}

// SetTimeWindows gets a reference to the given []TimeWindow and assigns it to the TimeWindows field.
func (o *Service) SetTimeWindows(v []TimeWindow) {
	o.TimeWindows = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Service) GetSize() []int32 {
	if o == nil || IsNil(o.Size) {
		var ret []int32
		return ret
	}
	return o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetSizeOk() ([]int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Service) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given []int32 and assigns it to the Size field.
func (o *Service) SetSize(v []int32) {
	o.Size = v
}

// GetRequiredSkills returns the RequiredSkills field value if set, zero value otherwise.
func (o *Service) GetRequiredSkills() []string {
	if o == nil || IsNil(o.RequiredSkills) {
		var ret []string
		return ret
	}
	return o.RequiredSkills
}

// GetRequiredSkillsOk returns a tuple with the RequiredSkills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetRequiredSkillsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredSkills) {
		return nil, false
	}
	return o.RequiredSkills, true
}

// HasRequiredSkills returns a boolean if a field has been set.
func (o *Service) HasRequiredSkills() bool {
	if o != nil && !IsNil(o.RequiredSkills) {
		return true
	}

	return false
}

// SetRequiredSkills gets a reference to the given []string and assigns it to the RequiredSkills field.
func (o *Service) SetRequiredSkills(v []string) {
	o.RequiredSkills = v
}

// GetAllowedVehicles returns the AllowedVehicles field value if set, zero value otherwise.
func (o *Service) GetAllowedVehicles() []string {
	if o == nil || IsNil(o.AllowedVehicles) {
		var ret []string
		return ret
	}
	return o.AllowedVehicles
}

// GetAllowedVehiclesOk returns a tuple with the AllowedVehicles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetAllowedVehiclesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedVehicles) {
		return nil, false
	}
	return o.AllowedVehicles, true
}

// HasAllowedVehicles returns a boolean if a field has been set.
func (o *Service) HasAllowedVehicles() bool {
	if o != nil && !IsNil(o.AllowedVehicles) {
		return true
	}

	return false
}

// SetAllowedVehicles gets a reference to the given []string and assigns it to the AllowedVehicles field.
func (o *Service) SetAllowedVehicles(v []string) {
	o.AllowedVehicles = v
}

// GetDisallowedVehicles returns the DisallowedVehicles field value if set, zero value otherwise.
func (o *Service) GetDisallowedVehicles() []string {
	if o == nil || IsNil(o.DisallowedVehicles) {
		var ret []string
		return ret
	}
	return o.DisallowedVehicles
}

// GetDisallowedVehiclesOk returns a tuple with the DisallowedVehicles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetDisallowedVehiclesOk() ([]string, bool) {
	if o == nil || IsNil(o.DisallowedVehicles) {
		return nil, false
	}
	return o.DisallowedVehicles, true
}

// HasDisallowedVehicles returns a boolean if a field has been set.
func (o *Service) HasDisallowedVehicles() bool {
	if o != nil && !IsNil(o.DisallowedVehicles) {
		return true
	}

	return false
}

// SetDisallowedVehicles gets a reference to the given []string and assigns it to the DisallowedVehicles field.
func (o *Service) SetDisallowedVehicles(v []string) {
	o.DisallowedVehicles = v
}

// GetPreferredVehicles returns the PreferredVehicles field value if set, zero value otherwise.
func (o *Service) GetPreferredVehicles() []PreferredVehicle {
	if o == nil || IsNil(o.PreferredVehicles) {
		var ret []PreferredVehicle
		return ret
	}
	return o.PreferredVehicles
}

// GetPreferredVehiclesOk returns a tuple with the PreferredVehicles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetPreferredVehiclesOk() ([]PreferredVehicle, bool) {
	if o == nil || IsNil(o.PreferredVehicles) {
		return nil, false
	}
	return o.PreferredVehicles, true
}

// HasPreferredVehicles returns a boolean if a field has been set.
func (o *Service) HasPreferredVehicles() bool {
	if o != nil && !IsNil(o.PreferredVehicles) {
		return true
	}

	return false
}

// SetPreferredVehicles gets a reference to the given []PreferredVehicle and assigns it to the PreferredVehicles field.
func (o *Service) SetPreferredVehicles(v []PreferredVehicle) {
	o.PreferredVehicles = v
}

// GetMaxTimeInVehicle returns the MaxTimeInVehicle field value if set, zero value otherwise.
func (o *Service) GetMaxTimeInVehicle() int64 {
	if o == nil || IsNil(o.MaxTimeInVehicle) {
		var ret int64
		return ret
	}
	return *o.MaxTimeInVehicle
}

// GetMaxTimeInVehicleOk returns a tuple with the MaxTimeInVehicle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetMaxTimeInVehicleOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxTimeInVehicle) {
		return nil, false
	}
	return o.MaxTimeInVehicle, true
}

// HasMaxTimeInVehicle returns a boolean if a field has been set.
func (o *Service) HasMaxTimeInVehicle() bool {
	if o != nil && !IsNil(o.MaxTimeInVehicle) {
		return true
	}

	return false
}

// SetMaxTimeInVehicle gets a reference to the given int64 and assigns it to the MaxTimeInVehicle field.
func (o *Service) SetMaxTimeInVehicle(v int64) {
	o.MaxTimeInVehicle = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *Service) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Service) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *Service) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *Service) SetGroup(v string) {
	o.Group = &v
}

func (o Service) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Service) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.PreparationTime) {
		toSerialize["preparation_time"] = o.PreparationTime
	}
	if !IsNil(o.TimeWindows) {
		toSerialize["time_windows"] = o.TimeWindows
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.RequiredSkills) {
		toSerialize["required_skills"] = o.RequiredSkills
	}
	if !IsNil(o.AllowedVehicles) {
		toSerialize["allowed_vehicles"] = o.AllowedVehicles
	}
	if !IsNil(o.DisallowedVehicles) {
		toSerialize["disallowed_vehicles"] = o.DisallowedVehicles
	}
	if !IsNil(o.PreferredVehicles) {
		toSerialize["preferred_vehicles"] = o.PreferredVehicles
	}
	if !IsNil(o.MaxTimeInVehicle) {
		toSerialize["max_time_in_vehicle"] = o.MaxTimeInVehicle
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

func (o *Service) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varService := _Service{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varService)

	if err != nil {
		return err
	}

	*o = Service(varService)

	return err
}

type NullableService struct {
	value *Service
	isSet bool
}

func (v NullableService) Get() *Service {
	return v.value
}

func (v *NullableService) Set(val *Service) {
	v.value = val
	v.isSet = true
}

func (v NullableService) IsSet() bool {
	return v.isSet
}

func (v *NullableService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableService(val *Service) *NullableService {
	return &NullableService{value: val, isSet: true}
}

func (v NullableService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


