/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FeatureCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureCollection{}

// FeatureCollection struct for FeatureCollection
type FeatureCollection struct {
	Type *string `json:"type,omitempty"`
	// A FeatureCollection is an array of type \"Feature\" from GeoJSON
	Features []FeatureCollectionFeaturesInner `json:"features,omitempty"`
}

// NewFeatureCollection instantiates a new FeatureCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureCollection() *FeatureCollection {
	this := FeatureCollection{}
	return &this
}

// NewFeatureCollectionWithDefaults instantiates a new FeatureCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureCollectionWithDefaults() *FeatureCollection {
	this := FeatureCollection{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FeatureCollection) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureCollection) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FeatureCollection) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FeatureCollection) SetType(v string) {
	o.Type = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *FeatureCollection) GetFeatures() []FeatureCollectionFeaturesInner {
	if o == nil || IsNil(o.Features) {
		var ret []FeatureCollectionFeaturesInner
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureCollection) GetFeaturesOk() ([]FeatureCollectionFeaturesInner, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *FeatureCollection) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []FeatureCollectionFeaturesInner and assigns it to the Features field.
func (o *FeatureCollection) SetFeatures(v []FeatureCollectionFeaturesInner) {
	o.Features = v
}

func (o FeatureCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	return toSerialize, nil
}

type NullableFeatureCollection struct {
	value *FeatureCollection
	isSet bool
}

func (v NullableFeatureCollection) Get() *FeatureCollection {
	return v.value
}

func (v *NullableFeatureCollection) Set(val *FeatureCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureCollection(val *FeatureCollection) *NullableFeatureCollection {
	return &NullableFeatureCollection{value: val, isSet: true}
}

func (v NullableFeatureCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


