/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterConfigurationClustering type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterConfigurationClustering{}

// ClusterConfigurationClustering struct for ClusterConfigurationClustering
type ClusterConfigurationClustering struct {
	// Specifies the number of clusters
	NumClusters *float32 `json:"num_clusters,omitempty"`
	// Specifies max. quantity in a cluster
	MaxQuantity *float32 `json:"max_quantity,omitempty"`
	// Specifies min. quantity in a cluster
	MinQuantity *float32 `json:"min_quantity,omitempty"`
}

// NewClusterConfigurationClustering instantiates a new ClusterConfigurationClustering object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterConfigurationClustering() *ClusterConfigurationClustering {
	this := ClusterConfigurationClustering{}
	return &this
}

// NewClusterConfigurationClusteringWithDefaults instantiates a new ClusterConfigurationClustering object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterConfigurationClusteringWithDefaults() *ClusterConfigurationClustering {
	this := ClusterConfigurationClustering{}
	return &this
}

// GetNumClusters returns the NumClusters field value if set, zero value otherwise.
func (o *ClusterConfigurationClustering) GetNumClusters() float32 {
	if o == nil || IsNil(o.NumClusters) {
		var ret float32
		return ret
	}
	return *o.NumClusters
}

// GetNumClustersOk returns a tuple with the NumClusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigurationClustering) GetNumClustersOk() (*float32, bool) {
	if o == nil || IsNil(o.NumClusters) {
		return nil, false
	}
	return o.NumClusters, true
}

// HasNumClusters returns a boolean if a field has been set.
func (o *ClusterConfigurationClustering) HasNumClusters() bool {
	if o != nil && !IsNil(o.NumClusters) {
		return true
	}

	return false
}

// SetNumClusters gets a reference to the given float32 and assigns it to the NumClusters field.
func (o *ClusterConfigurationClustering) SetNumClusters(v float32) {
	o.NumClusters = &v
}

// GetMaxQuantity returns the MaxQuantity field value if set, zero value otherwise.
func (o *ClusterConfigurationClustering) GetMaxQuantity() float32 {
	if o == nil || IsNil(o.MaxQuantity) {
		var ret float32
		return ret
	}
	return *o.MaxQuantity
}

// GetMaxQuantityOk returns a tuple with the MaxQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigurationClustering) GetMaxQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxQuantity) {
		return nil, false
	}
	return o.MaxQuantity, true
}

// HasMaxQuantity returns a boolean if a field has been set.
func (o *ClusterConfigurationClustering) HasMaxQuantity() bool {
	if o != nil && !IsNil(o.MaxQuantity) {
		return true
	}

	return false
}

// SetMaxQuantity gets a reference to the given float32 and assigns it to the MaxQuantity field.
func (o *ClusterConfigurationClustering) SetMaxQuantity(v float32) {
	o.MaxQuantity = &v
}

// GetMinQuantity returns the MinQuantity field value if set, zero value otherwise.
func (o *ClusterConfigurationClustering) GetMinQuantity() float32 {
	if o == nil || IsNil(o.MinQuantity) {
		var ret float32
		return ret
	}
	return *o.MinQuantity
}

// GetMinQuantityOk returns a tuple with the MinQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigurationClustering) GetMinQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.MinQuantity) {
		return nil, false
	}
	return o.MinQuantity, true
}

// HasMinQuantity returns a boolean if a field has been set.
func (o *ClusterConfigurationClustering) HasMinQuantity() bool {
	if o != nil && !IsNil(o.MinQuantity) {
		return true
	}

	return false
}

// SetMinQuantity gets a reference to the given float32 and assigns it to the MinQuantity field.
func (o *ClusterConfigurationClustering) SetMinQuantity(v float32) {
	o.MinQuantity = &v
}

func (o ClusterConfigurationClustering) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterConfigurationClustering) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NumClusters) {
		toSerialize["num_clusters"] = o.NumClusters
	}
	if !IsNil(o.MaxQuantity) {
		toSerialize["max_quantity"] = o.MaxQuantity
	}
	if !IsNil(o.MinQuantity) {
		toSerialize["min_quantity"] = o.MinQuantity
	}
	return toSerialize, nil
}

type NullableClusterConfigurationClustering struct {
	value *ClusterConfigurationClustering
	isSet bool
}

func (v NullableClusterConfigurationClustering) Get() *ClusterConfigurationClustering {
	return v.value
}

func (v *NullableClusterConfigurationClustering) Set(val *ClusterConfigurationClustering) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterConfigurationClustering) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterConfigurationClustering) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterConfigurationClustering(val *ClusterConfigurationClustering) *NullableClusterConfigurationClustering {
	return &NullableClusterConfigurationClustering{value: val, isSet: true}
}

func (v NullableClusterConfigurationClustering) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterConfigurationClustering) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


