/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CostMatrix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostMatrix{}

// CostMatrix struct for CostMatrix
type CostMatrix struct {
	// type of cost matrix, currently default or google are supported
	Type *string `json:"type,omitempty"`
	LocationIds []string `json:"location_ids,omitempty"`
	Data *CostMatrixData `json:"data,omitempty"`
	// vehicle profile or empty if catch all fallback
	Profile *string `json:"profile,omitempty"`
}

// NewCostMatrix instantiates a new CostMatrix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostMatrix() *CostMatrix {
	this := CostMatrix{}
	return &this
}

// NewCostMatrixWithDefaults instantiates a new CostMatrix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostMatrixWithDefaults() *CostMatrix {
	this := CostMatrix{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CostMatrix) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrix) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CostMatrix) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CostMatrix) SetType(v string) {
	o.Type = &v
}

// GetLocationIds returns the LocationIds field value if set, zero value otherwise.
func (o *CostMatrix) GetLocationIds() []string {
	if o == nil || IsNil(o.LocationIds) {
		var ret []string
		return ret
	}
	return o.LocationIds
}

// GetLocationIdsOk returns a tuple with the LocationIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrix) GetLocationIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.LocationIds) {
		return nil, false
	}
	return o.LocationIds, true
}

// HasLocationIds returns a boolean if a field has been set.
func (o *CostMatrix) HasLocationIds() bool {
	if o != nil && !IsNil(o.LocationIds) {
		return true
	}

	return false
}

// SetLocationIds gets a reference to the given []string and assigns it to the LocationIds field.
func (o *CostMatrix) SetLocationIds(v []string) {
	o.LocationIds = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CostMatrix) GetData() CostMatrixData {
	if o == nil || IsNil(o.Data) {
		var ret CostMatrixData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrix) GetDataOk() (*CostMatrixData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CostMatrix) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CostMatrixData and assigns it to the Data field.
func (o *CostMatrix) SetData(v CostMatrixData) {
	o.Data = &v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *CostMatrix) GetProfile() string {
	if o == nil || IsNil(o.Profile) {
		var ret string
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostMatrix) GetProfileOk() (*string, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *CostMatrix) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given string and assigns it to the Profile field.
func (o *CostMatrix) SetProfile(v string) {
	o.Profile = &v
}

func (o CostMatrix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostMatrix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.LocationIds) {
		toSerialize["location_ids"] = o.LocationIds
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	return toSerialize, nil
}

type NullableCostMatrix struct {
	value *CostMatrix
	isSet bool
}

func (v NullableCostMatrix) Get() *CostMatrix {
	return v.value
}

func (v *NullableCostMatrix) Set(val *CostMatrix) {
	v.value = val
	v.isSet = true
}

func (v NullableCostMatrix) IsSet() bool {
	return v.isSet
}

func (v *NullableCostMatrix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostMatrix(val *CostMatrix) *NullableCostMatrix {
	return &NullableCostMatrix{value: val, isSet: true}
}

func (v NullableCostMatrix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostMatrix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


