/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseInfo{}

// ResponseInfo Additional information for your request
type ResponseInfo struct {
	// Attribution according to our documentation is necessary if no white-label option included.
	Copyrights []string `json:"copyrights,omitempty"`
	Took *float64 `json:"took,omitempty"`
}

// NewResponseInfo instantiates a new ResponseInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseInfo() *ResponseInfo {
	this := ResponseInfo{}
	return &this
}

// NewResponseInfoWithDefaults instantiates a new ResponseInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseInfoWithDefaults() *ResponseInfo {
	this := ResponseInfo{}
	return &this
}

// GetCopyrights returns the Copyrights field value if set, zero value otherwise.
func (o *ResponseInfo) GetCopyrights() []string {
	if o == nil || IsNil(o.Copyrights) {
		var ret []string
		return ret
	}
	return o.Copyrights
}

// GetCopyrightsOk returns a tuple with the Copyrights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfo) GetCopyrightsOk() ([]string, bool) {
	if o == nil || IsNil(o.Copyrights) {
		return nil, false
	}
	return o.Copyrights, true
}

// HasCopyrights returns a boolean if a field has been set.
func (o *ResponseInfo) HasCopyrights() bool {
	if o != nil && !IsNil(o.Copyrights) {
		return true
	}

	return false
}

// SetCopyrights gets a reference to the given []string and assigns it to the Copyrights field.
func (o *ResponseInfo) SetCopyrights(v []string) {
	o.Copyrights = v
}

// GetTook returns the Took field value if set, zero value otherwise.
func (o *ResponseInfo) GetTook() float64 {
	if o == nil || IsNil(o.Took) {
		var ret float64
		return ret
	}
	return *o.Took
}

// GetTookOk returns a tuple with the Took field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfo) GetTookOk() (*float64, bool) {
	if o == nil || IsNil(o.Took) {
		return nil, false
	}
	return o.Took, true
}

// HasTook returns a boolean if a field has been set.
func (o *ResponseInfo) HasTook() bool {
	if o != nil && !IsNil(o.Took) {
		return true
	}

	return false
}

// SetTook gets a reference to the given float64 and assigns it to the Took field.
func (o *ResponseInfo) SetTook(v float64) {
	o.Took = &v
}

func (o ResponseInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Copyrights) {
		toSerialize["copyrights"] = o.Copyrights
	}
	if !IsNil(o.Took) {
		toSerialize["took"] = o.Took
	}
	return toSerialize, nil
}

type NullableResponseInfo struct {
	value *ResponseInfo
	isSet bool
}

func (v NullableResponseInfo) Get() *ResponseInfo {
	return v.value
}

func (v *NullableResponseInfo) Set(val *ResponseInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseInfo(val *ResponseInfo) *NullableResponseInfo {
	return &NullableResponseInfo{value: val, isSet: true}
}

func (v NullableResponseInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


