/*
GraphHopper Directions API

 Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/#/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in our [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 

API version: 1.0.0
Contact: support@graphhopper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IsochroneResponsePolygonProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsochroneResponsePolygonProperties{}

// IsochroneResponsePolygonProperties struct for IsochroneResponsePolygonProperties
type IsochroneResponsePolygonProperties struct {
	Bucket *int32 `json:"bucket,omitempty"`
}

// NewIsochroneResponsePolygonProperties instantiates a new IsochroneResponsePolygonProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsochroneResponsePolygonProperties() *IsochroneResponsePolygonProperties {
	this := IsochroneResponsePolygonProperties{}
	return &this
}

// NewIsochroneResponsePolygonPropertiesWithDefaults instantiates a new IsochroneResponsePolygonProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsochroneResponsePolygonPropertiesWithDefaults() *IsochroneResponsePolygonProperties {
	this := IsochroneResponsePolygonProperties{}
	return &this
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *IsochroneResponsePolygonProperties) GetBucket() int32 {
	if o == nil || IsNil(o.Bucket) {
		var ret int32
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsochroneResponsePolygonProperties) GetBucketOk() (*int32, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *IsochroneResponsePolygonProperties) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given int32 and assigns it to the Bucket field.
func (o *IsochroneResponsePolygonProperties) SetBucket(v int32) {
	o.Bucket = &v
}

func (o IsochroneResponsePolygonProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsochroneResponsePolygonProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	return toSerialize, nil
}

type NullableIsochroneResponsePolygonProperties struct {
	value *IsochroneResponsePolygonProperties
	isSet bool
}

func (v NullableIsochroneResponsePolygonProperties) Get() *IsochroneResponsePolygonProperties {
	return v.value
}

func (v *NullableIsochroneResponsePolygonProperties) Set(val *IsochroneResponsePolygonProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableIsochroneResponsePolygonProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableIsochroneResponsePolygonProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsochroneResponsePolygonProperties(val *IsochroneResponsePolygonProperties) *NullableIsochroneResponsePolygonProperties {
	return &NullableIsochroneResponsePolygonProperties{value: val, isSet: true}
}

func (v NullableIsochroneResponsePolygonProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsochroneResponsePolygonProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


